// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: person/person.proto

package pbtest.person;

public interface PersonOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pbtest.person.Person)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string name = 1;</code>
   * @return Whether the name field is set.
   */
  boolean hasName();
  /**
   * <code>optional string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>optional string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>optional int32 id = 2;</code>
   * @return Whether the id field is set.
   */
  boolean hasId();
  /**
   * <code>optional int32 id = 2;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>optional string email = 3;</code>
   * @return Whether the email field is set.
   */
  boolean hasEmail();
  /**
   * <code>optional string email = 3;</code>
   * @return The email.
   */
  java.lang.String getEmail();
  /**
   * <code>optional string email = 3;</code>
   * @return The bytes for email.
   */
  com.google.protobuf.ByteString
      getEmailBytes();

  /**
   * <code>optional .google.protobuf.Timestamp dob = 5;</code>
   * @return Whether the dob field is set.
   */
  boolean hasDob();
  /**
   * <code>optional .google.protobuf.Timestamp dob = 5;</code>
   * @return The dob.
   */
  com.google.protobuf.Timestamp getDob();
  /**
   * <code>optional .google.protobuf.Timestamp dob = 5;</code>
   */
  com.google.protobuf.TimestampOrBuilder getDobOrBuilder();

  /**
   * <code>repeated .pbtest.person.Person.PhoneNumber phones = 4;</code>
   */
  java.util.List<pbtest.person.Person.PhoneNumber> 
      getPhonesList();
  /**
   * <code>repeated .pbtest.person.Person.PhoneNumber phones = 4;</code>
   */
  pbtest.person.Person.PhoneNumber getPhones(int index);
  /**
   * <code>repeated .pbtest.person.Person.PhoneNumber phones = 4;</code>
   */
  int getPhonesCount();
  /**
   * <code>repeated .pbtest.person.Person.PhoneNumber phones = 4;</code>
   */
  java.util.List<? extends pbtest.person.Person.PhoneNumberOrBuilder> 
      getPhonesOrBuilderList();
  /**
   * <code>repeated .pbtest.person.Person.PhoneNumber phones = 4;</code>
   */
  pbtest.person.Person.PhoneNumberOrBuilder getPhonesOrBuilder(
      int index);
}
