// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/addressbook.proto

package pbtest;

public interface AddressBookOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pbtest.AddressBook)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .pbtest.Person people = 1;</code>
   */
  java.util.List<pbtest.Person> 
      getPeopleList();
  /**
   * <code>repeated .pbtest.Person people = 1;</code>
   */
  pbtest.Person getPeople(int index);
  /**
   * <code>repeated .pbtest.Person people = 1;</code>
   */
  int getPeopleCount();
  /**
   * <code>repeated .pbtest.Person people = 1;</code>
   */
  java.util.List<? extends pbtest.PersonOrBuilder> 
      getPeopleOrBuilderList();
  /**
   * <code>repeated .pbtest.Person people = 1;</code>
   */
  pbtest.PersonOrBuilder getPeopleOrBuilder(
      int index);
}
