// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: addressbook.proto

package pbtest;

public interface AddressBookOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pbtest.AddressBook)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .pbtest.person.Person people = 1;</code>
   */
  java.util.List<pbtest.person.Person> 
      getPeopleList();
  /**
   * <code>repeated .pbtest.person.Person people = 1;</code>
   */
  pbtest.person.Person getPeople(int index);
  /**
   * <code>repeated .pbtest.person.Person people = 1;</code>
   */
  int getPeopleCount();
  /**
   * <code>repeated .pbtest.person.Person people = 1;</code>
   */
  java.util.List<? extends pbtest.person.PersonOrBuilder> 
      getPeopleOrBuilderList();
  /**
   * <code>repeated .pbtest.person.Person people = 1;</code>
   */
  pbtest.person.PersonOrBuilder getPeopleOrBuilder(
      int index);
}
